backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# These lines should *not* be indented
media_folder: "public/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "event" # Used in routes, e.g., /admin/collections/blog
    label: "Event" # Used in the UI
    identifier_field: title
    folder: "src/content/events" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{title}}" # Filename template, e.gf., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter 
      - {label: "Layout", name: "layout", widget: "hidden", default: "../../layouts/EventLayout.astro"}
      - {label: "Active", name: "active", widget: "boolean", default: true}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Caption", name: "description", widget: "string", required: false}
      - {label: "Event Date", name: "date", widget: "datetime", time_format:"HH:mm", date_format: "ddd mmmm, yyyy"}
      - {label: "Image (560 x 315px) .webp", name: "image", widget: "image", required: false}
      - {label: "Audio URL", name: "audiourl", widget: "string", required: false}
      - {label: "Video URL", name: "videourl", widget: "string", required: false}
      - {label: "Body", name: "body", widget: "markdown", required: false}
  - name: "member" # Used in routes, e.g., /admin/collections/members
    label: "Member" # Used in the UI
    identifier_field: acronym
    folder: "src/content/members" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{fullname}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter 
      - {label: "Layout", name: "layout", widget: "hidden", default: "../../layouts/MemberLayout.astro"}
      - {label: "Acronym", name: "acronym", widget: "string"}
      - {label: "Full name", name: "fullname", widget: "string"}
      - {label: "Category", name: "category", widget: "string"}
      - {label: "Website URL", name: "website", widget: "string"}
      - {label: "Logo (800 x 800 or any highres dimension)", name: "logo", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown", required: false}
  - name: "team" # Used in routes, e.g., /admin/collections/members
    label: "Team" # Used in the UI
    identifier_field: name
    folder: "src/content/team" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{name}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter 
      - {label: "Layout", name: "layout", widget: "hidden", default: "../../layouts/TeamLayout.astro"}
      - {label: "Order", name: "order", widget: "number"}
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Acronym", name: "acronym", widget: "string", required: false}
      - {label: "Role", name: "role", widget: "string"}
      - {label: "Picture (800 x 800 or any highres dimension)", name: "picture", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown", required: false}
  - name: "slider" # Used in routes, e.g., /admin/collections/slider
    label: "Slider" # Used in the UI
    identifier_field: name
    folder: "src/content/sliders" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{name}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter 
      - {label: "Layout", name: "layout", widget: "hidden", default: "../../layouts/SliderLayout.astro"}
      - {label: "Active", name: "active", widget: "boolean", default: true}
      - {label: "Start Date", name: "date", widget: "datetime", required: false}
      - {label: "Name", name: "name", widget: "string"} 
      - {label: "Venue", name: "venue", widget: "string", required: false}
      - {label: "Map Location", name: "map", widget: "string", required: false}
      - {label: "Theme", name: "theme", widget: "string", required: false}
      - {label: "Host", name: "host", widget: "string", required: false}
      - {label: "Chairman", name: "chairman", widget: "string", required: false}
      - {label: "Keynote Speaker", name: "keynotespeaker", widget: "string", required: false}
      - {label: "Video URL", name: "videourl", widget: "string", required: false}
      - {label: "Website", name: "website", widget: "string", required: false}
      - {label: "Desktop Advertising Image (1920 x 400)", name: "dkimage", widget: "image", required: false}
      - {label: "Mobile Advertising Image (1326 x 602)", name: "mbimage", widget: "image", required: false}
      - {label: "APBN Event Image (1326 x 602)", name: "image", widget: "image", required: false}
      - {label: "Slider Type", name: "type", widget: "select", options: ["APBN", "Advertising"]}
      - {label: "Body", name: "body", widget: "markdown", required: false}
  - name: "resources" # Used in routes, e.g., /admin/collections/resources
    label: "Resources" # Used in the UI 
    folder: "src/pages/resources" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{name}}" # Filename template, e.g., YYYY-MM-DD-title.md
    identifier_field: name
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "../../layouts/ResourcesLayout.astro"}
      - {label: "Active", name: "active", widget: "boolean", default: true}
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Form Title", name: "formtitle", widget: "string", required: false}
      - {
          label: "Input Fields",
          name: "inputfields",
          widget: "list",
          allow_add: true,
          required: false,
          summary: '{{fields.name}}',
          fields: [
            {label: "Field", name: "field", widget: "select", options: ["input", "textarea", "select"]},
            {label: "Name (no spaces btw words)", name: "name", widget: "string"},
            {label: "Type", name: "type", widget: "select", options: ["text", "tel", "email", "number", "date", "file"], required: false},
            {label: "Placeholder", name: "placeholder", widget: "string"}
          ]
        }
      - {label: "Body", name: "body", widget: "markdown", required: false}